"use client";

import { useState, useTransition } from "react";
import { reversePlatformPayment } from "@/app/actions/admin";

export function ReversePlatformPaymentButton({ paymentId, label }: { paymentId: string; label: string }) {
  const [open, setOpen] = useState(false); const [reason, setReason] = useState(""); const [error, setError] = useState(""); const [pending, startTransition] = useTransition();
  return <><button type="button" className="secondary" onClick={() => setOpen(true)} style={{ minHeight: 26, height: 26, fontSize: 10 }}>Annuler</button>{open && <div style={{ position: "fixed", inset: 0, zIndex: 1300, display: "grid", placeItems: "center", padding: 20, background: "rgba(0,0,0,.74)", backdropFilter: "blur(5px)" }} onMouseDown={(event) => { if (event.target === event.currentTarget && !pending) setOpen(false); }}><div style={{ width: "min(450px,100%)", padding: 22, borderRadius: 14, background: "var(--sr-surface)", border: "1px solid var(--sr-danger-border)" }}><h3 style={{ marginTop: 0 }}>Annuler cet encaissement ?</h3><p style={{ color: "var(--sr-fg-subtle)", fontSize: 12 }}>{label}. L’écriture initiale restera visible et une contre-écriture sera créée. Le plan appliqué ne sera pas modifié automatiquement.</p><label>Motif<textarea value={reason} onChange={(event) => setReason(event.target.value)} maxLength={300} placeholder="Ex. paiement enregistré deux fois" /></label>{error && <p style={{ color: "var(--sr-danger)", fontSize: 12 }}>{error}</p>}<div style={{ display: "flex", justifyContent: "flex-end", gap: 8, marginTop: 18 }}><button type="button" className="secondary" disabled={pending} onClick={() => setOpen(false)}>Fermer</button><button type="button" className="danger" disabled={pending || reason.trim().length < 3} onClick={() => startTransition(async () => { try { await reversePlatformPayment(paymentId, reason); setOpen(false); } catch (caught) { setError(caught instanceof Error ? caught.message : "Annulation impossible"); } })}>{pending ? "Traitement…" : "Confirmer l’annulation"}</button></div></div></div>}</>;
}
