import { APP_VERSION, RELEASE_DATE } from "@/lib/version";

const guides = [
  ["1", "Ajouter un compte", "Ouvrez Mes abonnements, choisissez le service, le nombre de profils et la durée du compte fournisseur."],
  ["2", "Inscrire un client", "Dans Mes clients, choisissez Nouveau client, sélectionnez un profil libre puis renseignez le paiement."],
  ["3", "Envoyer la facture", "Ouvrez la fiche client, puis utilisez WhatsApp, Partager ou Télécharger PDF dans la section Factures."],
  ["4", "Suivre les échéances", "Le dashboard, la cloche et les notifications push indiquent les clients à relancer et les packs proches de leur fin."],
];

export default function HelpPage() {
  return <><div className="dash-header"><p className="dash-eyebrow">Centre d’aide</p><h1>Utiliser SubResell</h1><p className="dash-header-sub">Les principaux parcours, expliqués simplement.</p></div><div className="panel" style={{ marginBottom: 20 }}><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: 12 }}>{guides.map(([number,title,text]) => <article key={number} style={{ padding: 16, borderRadius: 10, border: "1px solid var(--sr-border-subtle)", background: "var(--sr-bg)" }}><span style={{ width: 28, height: 28, display: "grid", placeItems: "center", borderRadius: 8, background: "var(--sr-success-bg)", color: "var(--sr-success)", fontWeight: 700 }}>{number}</span><h2 style={{ margin: "14px 0 7px", fontSize: 15 }}>{title}</h2><p style={{ margin: 0, color: "var(--sr-fg-subtle)", fontSize: 12, lineHeight: 1.55 }}>{text}</p></article>)}</div></div><div className="dash-grid-2"><section className="panel"><p className="eyebrow">Questions fréquentes</p><h2>Paiements et abonnements</h2><details><summary>Un compte extra prolonge-t-il le pack ?</summary><p>Non. Il augmente uniquement le nombre de comptes disponibles sur un pack Pro encore actif.</p></details><details><summary>Que fait une annulation comptable ?</summary><p>Elle conserve l’écriture initiale et crée une écriture inverse pour préserver la traçabilité.</p></details><details><summary>Comment installer l’application ?</summary><p>Utilisez le bouton Installer dans la barre supérieure ou dans Mon profil → Application.</p></details></section><section className="panel"><p className="eyebrow">Notes de version</p><h2>Version {APP_VERSION}</h2><p style={{ color: "var(--sr-fg-subtle)", fontSize: 12 }}>Publiée le {RELEASE_DATE}</p><ul style={{ color: "var(--sr-fg-muted)", fontSize: 12, lineHeight: 1.8 }}><li>Centre de notifications et recherche globale</li><li>Import CSV, sauvegarde et restauration</li><li>Annulations comptables traçables</li><li>Factures PDF, QR code et statuts</li><li>Fusion, archivage et historique client</li><li>Améliorations admin, mobile et accessibilité</li></ul></section></div></>;
}
