"use client";
import { useLocale } from "next-intl";
import { useEffect, useRef } from "react";
import { UI_EN, UI_EN_EXTRA, UI_EN_PATTERNS } from "@/i18n/ui-dictionary";

const ATTRS=["placeholder","title","aria-label"] as const;
function translate(value:string){const lead=value.match(/^\s*/)?.[0]??"";const tail=value.match(/\s*$/)?.[0]??"";const core=value.trim();if(!core)return value;let next=UI_EN_EXTRA[core]??UI_EN[core]??core;if(next===core)for(const[pattern,replacement]of UI_EN_PATTERNS)next=next.replace(pattern,replacement);return lead+next+tail;}

export function RuntimeI18n(){const locale=useLocale();const originals=useRef(new Map<Node,string>());const attributes=useRef(new Map<Element,Map<string,string>>());useEffect(()=>{const apply=(root:Node)=>{const visit=(node:Node)=>{if(node.nodeType===Node.TEXT_NODE){const parent=node.parentElement;if(!parent||["SCRIPT","STYLE","CODE","PRE"].includes(parent.tagName))return;if(!originals.current.has(node))originals.current.set(node,node.textContent??"");const original=originals.current.get(node)??"";const next=locale==="en"?translate(original):original;if(node.textContent!==next)node.textContent=next;return;}if(node instanceof Element){if(["SCRIPT","STYLE","CODE","PRE"].includes(node.tagName))return;let saved=attributes.current.get(node);if(!saved){saved=new Map();attributes.current.set(node,saved);}for(const attr of ATTRS){const current=node.getAttribute(attr);if(current!==null&&!saved.has(attr))saved.set(attr,current);const original=saved.get(attr);if(original!==undefined){const next=locale==="en"?translate(original):original;if(node.getAttribute(attr)!==next)node.setAttribute(attr,next);}}for(const child of node.childNodes)visit(child);}};visit(root);};apply(document.body);const observer=new MutationObserver(records=>{for(const record of records){if(record.type==="characterData")apply(record.target);for(const node of record.addedNodes)apply(node);}});observer.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>observer.disconnect();},[locale]);return null;}
